# VibeShare (SETBD) - Gradle configuration
org.gradle.jvmargs=-Xmx1280m -XX:MaxMetaspaceSize=448m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx1152m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
